name: tool
description: A simple command-line application.
version: 4.0.0-preview.6
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  mustache_template: ^2.0.0
  file: ^6.1.2
  args: ^2.3.0
  build_cli_annotations: ^2.0.0
  uuid: ^3.0.6
  process_run: ^0.12.3+2

dev_dependencies:
  lints: ^1.0.0
  build_cli: ^2.0.0
  build_runner: ^2.0.6
